return {
  -- {
  --   'stevearc/oil.nvim',
  --   ---@module 'oil'
  --   ---@type oil.SetupOpts
  --   opts = {},
  --   -- Optional dependencies
  --   dependencies = { { 'echasnovski/mini.icons', opts = {} } },
  --   -- dependencies = { "nvim-tree/nvim-web-devicons" }, -- use if prefer nvim-web-devicons
  --   config = function()
  --     require('oil').setup {
  --
  --       delete_to_trash = true,
  --       default_file_explorer = true,
  --     }
  --     CustomOilBar = function()
  --       local path = vim.fn.expand '%'
  --       path = path:gsub('oil://', '')
  --
  --       return '  ' .. vim.fn.fnamemodify(path, ':.')
  --     end
  --     vim.keymap.set('n', '-', '<CMD>Oil<CR>', { desc = 'Open parent directory' })
  --
  --     -- Open parent directory in floating window
  --     vim.keymap.set('n', '<leader>-', require('oil').toggle_float)
  --   end,
  -- },
}
